### PR TITLE
Move PineAPPL to yadbox

### PR DESCRIPTION
**Pull request by AleCandido**

### CODE REVIEW

**Comment by felixhekhorn** [comment]
How can we retrigger the workflows?

**Comment by AleCandido** [comment]
In theory you retrigger by going on the old workflow (in the actions tab), and clicking the button. But this commit was older than 6 months, so I believe the workflow have been canceled.

I had to rebase in any case, so now they have been re-triggered by the new commit :)

**Comment by AleCandido** [comment]
It looks like we are not tracking `yadbox` (and probably nor `yadmark`) in the coverage...

**Comment by felixhekhorn** [comment]
> It looks like we are not tracking `yadbox` (and probably nor `yadmark`) in the coverage...

looks like ... keep in mind to also adjust `pinecardsrunner` if you make a new release ...

**Comment by AleCandido** [comment]
> looks like ... keep in mind to also adjust `pinecardsrunner` if you make a new release ...

Luckily Poetry is serving us well: I could make a new release of `yadism` without breaking `runcardsrunner` (even though this was actually safe), since the version is pinned.
But yes, the moment I'll do `poetry update` in `runcardsrunner` with this I'll have to update the code as well :)

**Comment by felixhekhorn** [comment]
Feel free to merge when you're ready

**Comment by AleCandido** [comment]
> Feel free to merge when you're ready

Almost: adding `yadbox` to the coverage doubled the codecov reports in the checks, but it seems like they refer always to `yadism` only, so I'd like to understand if it is actually working or not...

In any case, soon I will merge :)

**Comment by AleCandido** [comment]
Actually, the double Codecov thing solved on its own, even though `yadbox` still seems to have no coverage.

At this point I would merge, and worry later about `yadbox` coverage (that is not top priority in any case).

**Comment by felixhekhorn** [comment]
in the past we said we can merge, is this still the case? then we should do it @AleCandido

**Comment by AleCandido** [comment]
We didn't much, I'm fairly confident it should work. But if you could test it (once and in a simple way, not a unit test) would be great!

**Comment by felixhekhorn** [comment]
I think this is good to merge, do you agree? @AleCandido 

It will trigger 0.12 since we're breaking the API, i.e. `pinefarm` has to be adjusted

**Comment by felixhekhorn** [comment]
by the way: the branch name is completely misleading - since this PR does not tackle #122

**Comment by AleCandido** [comment]
> I think this is good to merge, do you agree? @AleCandido

Agreed

> It will trigger 0.12 since we're breaking the API, i.e. `pinefarm` has to be adjusted

The moment we want to release to `master`, but there is no urgent need.

> by the way: the branch name is completely misleading - since this PR does not tackle #122

I have the feeling you did it in the first place (since you authored the commit, I just rebased later...).
However, I guess the initial idea was to do it. Simply, this PR has been left behind for a while, and the initial goal has not been reached. But it is fine to merge, and open a new one (if someone wants to address #122).

**Pull request merged**
