### PR TITLE
Fix anomalous dimension labels in eko 0.9.4

### PR DESCRIPTION
**Pull request by felixhekhorn**
note that this is not a problem in the released version as this is not happening in 0.9.1 (but indeed is happening in 0.9.4)

### CODE REVIEW

**Comment by AleCandido** [comment]
Unfortunately, v0.9.4 is compatible with v0.9.1 (so it follows the rules of '^'). So, no problem for `yadism` environment, but for `yadism` dependencies, they will have to manually pin the `eko` version as well.

However, that's a good thing to remember for the future, it would have been a solution even without fixing this.

Before merging I'll try to fix the tests (otherwise we won't have a release in any case).

**Comment by felixhekhorn** [comment]
I agree it was an oversight on the `eko` side (however, in some sense this is the price we're paying in not doing a gigantic QED PR, since we're constantly breaking (small) things ... meaning: e.g. https://github.com/N3PDF/eko/pull/115 should trigger a minor step)

**Comment by felixhekhorn** [comment]
> Before merging I'll try to fix the tests (otherwise we won't have a release in any case).

ah sorry, yes - thanks! (same problem of course ...)

**Comment by AleCandido** [comment]
Last run unfortunately is just bad: PyPI is currently down...

I will rerun tomorrow.

**Comment by AleCandido** [comment]
We're back to a green tick, I'd propose to merge :)

**Review by AleCandido — APPROVED** [review]

**Pull request merged**
